#! /bin/bash

if [ ! $1 ] ; then
  echo "Please specify a name for this instance."
  exit
fi

SOLRDIR=`readlink -f $0`
# Absolute path this script is in.
SOLRPATH=`dirname $SOLRDIR`
# Copy and rename this folder for Solr instance.
cp -r $SOLRPATH /opt/solr/solr-$1

# Add Solr instance info to Tomcat.
CONTEXT=$"<Context docBase=\"/opt/solr/solr-$1/solr.war\" debug=\"0\" crossContext=\"true\" >
   <Environment name=\"solr/home\" type=\"java.lang.String\" value=\"/opt/solr/solr-$1\" override=\"true\" />
</Context>"
echo "$CONTEXT">"/etc/tomcat6/Catalina/localhost/solr-$1.xml"

# Make sure file permissions are correct.
chmod g+xw /opt/solr/solr-$1
chown -R :tomcat6 /opt/solr/solr-$1
chmod -R g+w /opt/solr/solr-$1

# Restart tomcat to see changes.
sudo /etc/init.d/tomcat6 restart
echo "A solr instance has been created and can be visited on this server at :8080/solr-$1"
